### ISSUE TITLE
[Important][Suggestion] Please upgrade http

### ISSUE THREAD

**Issue by rmymrtin** [aissat/easy_localization_loader#23]
Hello, I wanted to update the libraries I installed on my mobile application, but when I put the latest version of http, it tells me that easy_localization_loader is dependent on http ^0.12.0+2

### Here is the entire error: 

```
Because every version of easy_localization_loader depends on http ^0.12.0+2 and hover depends on http ^0.13.0, easy_localization_loader is forbidden.

So, because hover depends on easy_localization_loader ^0.0.2, version solving failed.
pub get failed (1; So, because hover depends on easy_localization_loader ^0.0.2, version solving failed.)
exit code 1
```

Can you change the version of http?

**Comment by vandir** [comment]
Please upgrade also the other packages like `yaml`

**Comment by vandir** [comment]
Please review and accept #26

**Comment by Overman775** [comment]
PR #26
