### ISSUE TITLE
HTTP parameters for SmartNetworkLoader

### ISSUE THREAD

**Issue by Floul** [aissat/easy_localization_loader#37]
Sometimes it's needed to specify additional parameters for an HTTP request. In my case I need to pass an api token in the header to be able to get access to my localization service (Localizely). 
Currently the loader takes String URL. I think it would be better to change it to HTTP object instead, so user can shape the request as he\she needs. Just a suggestion.

**Comment by ariefwijaya** [comment]
ok I'll take this @aissat

**Comment by horlannn** [comment]
@aissat pls let me know when you complete it,I need it a lot

**Comment by aissat** [comment]
done easy_localization_loader: ^1.0.1
