### ISSUE TITLE
`connectivity_plus ^3.0.3` conflicts with `easy_localization_loader ^1.0.1+1`

### ISSUE THREAD

**Issue by liplum** [aissat/easy_localization_loader#46]
## What's Wrong
As of press time, the latest [connectivity_plus](https://pub.dev/packages/connectivity_plus) is v3.0.3, but easy_localization_loader still depends on the old one `^2.3.7`.

In [easy_localization_loader/pubspec.yaml](https://github.com/aissat/easy_localization_loader/blob/master/pubspec.yaml).
```
connectivity_plus: ^2.3.7
```
And `connectivity_plus` is used in [smart_network_asset_loader](https://github.com/aissat/easy_localization_loader/blob/0469058b11f65b92c4fdc7a2cbbf1900401df0d6/lib/src/smart_network_asset_loader.dart#L4).

## Log
```
Running "flutter pub get" in my_app...
Resolving dependencies...
Because my_app depends on easy_localization_loader ^1.0.1+1 which depends on connectivity_plus ^2.3.7, connectivity_plus ^2.3.7 is required.
So, because my_app depends on connectivity_plus ^3.0.3, version solving failed.
```

## My Solutions
1. To separate `smart_network_asset_loader` from the `easy_localization_loader`. As to [Single-responsibility principle](https://en.wikipedia.org/wiki/Single-responsibility_principle), an asset loader should not mess with the connectivity of user devices.
It sounds cumbersome, but there has been issued before:  #41 #36.
2. To upgrade `connectivity_plus` depenedency. It's straightforward.
3. Since every asset loader is in a single file, it's easy to copy which loader you want direcly without adding to pubspec.yaml.

**Comment by kpk-i710** [comment]
same problem
