### ISSUE TITLE
about how to implement easy_localization consuming a webservice that returns the language

### ISSUE THREAD

**Issue by ingpedroaraujo** [aissat/easy_localization_loader#52]
I have the following situation: 
I consume a service that returns, for example: 
{
"home": "Home",
"documents": "documents",
}

This would be for the translation into the Spanish language.

How could I implement easy_localization using that service that returns translations as the respective code is sent to it?"

**Comment by bw-flagship** [comment]
Did you try it with the HttpAssetLoader?

**Comment by ingpedroaraujo** [comment]
I was able to solve it by making use of the property: "asset Loader" by creating my own class in the configuration. Since with the easy localization loader, it was not possible due to the incompatibility of other packages that I have installed.
