### ISSUE TITLE
Null safety

### ISSUE THREAD

**Issue by Amrazyan** [aissat/easy_localization_loader#53]
Please add support for null safety
The current Dart SDK version is 3.1.0.

Because easy_localization_loader >=1.0.0 <1.0.1 depends on http ^0.13.1 and easy_localization_loader
  <1.0.0 doesn't support null safety, easy_localization_loader <1.0.1 requires http ^0.13.1.
And because easy_localization_loader >=1.0.1 depends on http ^0.13.5, every version of
  easy_localization_loader requires http ^0.13.1.
So, because serv_u depends on both http ^1.1.0 and easy_localization_loader any, version solving failed.

The lower bound of "sdk: '>=2.7.0 <3.0.0'" must be 2.12.0 or higher to enable null safety.

**Comment by bw-flagship** [comment]
Your problem is the http dependency. This is already updated in our code, but not released. @aissat could you release v2? (Or give me permissions to do so)

**Comment by bw-flagship** [comment]
@Amrazyan In the meantime you can use the latest version via git to solve your issue

**Comment by bw-flagship** [comment]
v2.0.0 is released, including newest dependencies
