### ISSUE TITLE
Connectivity_plus dependency update

### ISSUE THREAD

**Issue by AbdulazizRasulbek** [aissat/easy_localization_loader#55]
Connectivity_plus 5.0 update fixes Xcode 15 issue by updateing minimum supported version to ios 12.0 
please update connectivity_plus dependency. Because old versions crashed when running in real ios device
Related Issue https://github.com/fluttercommunity/plus_plugins/pull/2169

**Comment by AbdulazizRasulbek** [comment]
For now I am using Connectivity_plus 5.0.1 with dependency_overrides in pubspec.yaml

**Comment by bw-flagship** [comment]
@AbdulazizRasulbek Thanks for filing the issue. Maybe you can create a pull request to update the dependency?

**Comment by AbdulazizRasulbek** [comment]
@bw-flagship created pull request by updating package versions to latest version

**Comment by bw-flagship** [comment]
@AbdulazizRasulbek The PR is merged now 👍  For now, you can use a git reference to the main branch to have the newest version, until it is released

**Comment by AbdulazizRasulbek** [comment]
@bw-flagship thanks
