### ISSUE TITLE
Cannot upgrade sheet_loader_localization to the latest 0.3.0, since it depends on csv ^6.0.0 and easy_localization_loader depends on some lower version of csv, please upgrade

### ISSUE THREAD

**Issue by noskova** [aissat/easy_localization_loader#67]
When I try to upgrade sheet_loader_localization to the latest 0.3.0 I get the message:

Because easy_localization_loader >=1.0.1 depends on csv ^5.0.1 and sheet_loader_localization >=0.3.0 depends on csv ^6.0.0, easy_localization_loader >=1.0.1 is incompatible with sheet_loader_localization >=0.3.0.

Pleeease 🙏 upgrade the version of csv ASAP, because eventually following the chain of the different dependencies this prevents our team from upgrading Flutter to the latest version 3.22.

**Comment by bw-flagship** [comment]
@noskova thanks for opening the issue! I would like to invite you to create a PR for this :)

**Comment by noskova** [comment]
The issue was solved, thanks!
