### ISSUE TITLE
[Question] How JSON loader is working?

### ISSUE THREAD

**Issue by Maus3rSR** [aissat/easy_localization_loader#7]
https://github.com/aissat/easy_localization_loader/blob/master/lib/src/json_asset_loader.dart

I do not understand how you can load data from json file as the json asset_loader is not implemented?

Maybe the file asset loader is more appropriate as it contain "jsondecode" ?

https://github.com/aissat/easy_localization_loader/blob/master/lib/src/file_asset_loader.dart

**Comment by AnmolShahid** [comment]
I resolve it by customised code for my app.
Thank you. 
There must be multi json format like csv and ymal etc formate

**Comment by Overman775** [comment]
@Maus3rSR its emty loader for testing, use loader from easy_localization to load json
